services:
  mongodb:
    image: mongo:latest
    container_name: vakeel_vision_mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
